version: "3.4"
services:
  simba:
    container_name: simba-client
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules